# Generated by Django 4.1 on 2022-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Title',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
